-- Semilla de la tabla 'dewey': primer y segundo sumario de la CDD.
-- Ejecutar después de 01_schema.sql:
--   sqlite3 biblioteca.gpkg < sql/04_seed_dewey.sql
--
-- 10 clases + 90 divisiones. Las divisiones terminadas en '00' (000, 100, …)
-- no se repiten: coinciden con el código de su propia clase, que es la clave
-- primaria de la tabla.
--
-- Las 1000 secciones quedan fuera a propósito. La notación exacta de cada
-- libro se guarda íntegra en 'libros.dewey_codigo_completo', así que no se
-- pierde precisión: 'dewey_categoria_id' solo agrupa para poder navegar.
--
-- Es reejecutable: INSERT OR IGNORE no toca lo que ya exista.

-- Clases (primer sumario)
INSERT OR IGNORE INTO dewey (codigo, descripcion, nivel, padre_codigo) VALUES
    ('000', 'Obras generales, informática e información', 'clase', NULL),
    ('100', 'Filosofía y psicología', 'clase', NULL),
    ('200', 'Religión', 'clase', NULL),
    ('300', 'Ciencias sociales', 'clase', NULL),
    ('400', 'Lenguas', 'clase', NULL),
    ('500', 'Ciencias naturales y matemáticas', 'clase', NULL),
    ('600', 'Tecnología (ciencias aplicadas)', 'clase', NULL),
    ('700', 'Artes y recreación', 'clase', NULL),
    ('800', 'Literatura y retórica', 'clase', NULL),
    ('900', 'Historia y geografía', 'clase', NULL);


-- Divisiones (segundo sumario), cada una colgando de su clase
INSERT OR IGNORE INTO dewey (codigo, descripcion, nivel, padre_codigo) VALUES
    ('010', 'Bibliografía', 'division', '000'),
    ('020', 'Biblioteconomía y ciencias de la información', 'division', '000'),
    ('030', 'Enciclopedias y libros de datos generales', 'division', '000'),
    ('040', 'Sin asignar', 'division', '000'),
    ('050', 'Publicaciones seriadas generales', 'division', '000'),
    ('060', 'Organizaciones generales y museología', 'division', '000'),
    ('070', 'Medios de comunicación, periodismo y edición', 'division', '000'),
    ('080', 'Colecciones generales y citas', 'division', '000'),
    ('090', 'Manuscritos y libros raros', 'division', '000'),
    ('110', 'Metafísica', 'division', '100'),
    ('120', 'Epistemología, causalidad y humanidad', 'division', '100'),
    ('130', 'Fenómenos paranormales', 'division', '100'),
    ('140', 'Escuelas filosóficas específicas', 'division', '100'),
    ('150', 'Psicología', 'division', '100'),
    ('160', 'Lógica', 'division', '100'),
    ('170', 'Ética (filosofía moral)', 'division', '100'),
    ('180', 'Filosofía antigua, medieval y oriental', 'division', '100'),
    ('190', 'Filosofía occidental moderna', 'division', '100'),
    ('210', 'Filosofía y teoría de la religión', 'division', '200'),
    ('220', 'Biblia', 'division', '200'),
    ('230', 'Cristianismo y teología cristiana', 'division', '200'),
    ('240', 'Moral cristiana y teología devocional', 'division', '200'),
    ('250', 'Órdenes cristianas e iglesia local', 'division', '200'),
    ('260', 'Teología social cristiana', 'division', '200'),
    ('270', 'Historia del cristianismo', 'division', '200'),
    ('280', 'Confesiones y sectas cristianas', 'division', '200'),
    ('290', 'Otras religiones', 'division', '200'),
    ('310', 'Estadística', 'division', '300'),
    ('320', 'Ciencia política', 'division', '300'),
    ('330', 'Economía', 'division', '300'),
    ('340', 'Derecho', 'division', '300'),
    ('350', 'Administración pública y ciencia militar', 'division', '300'),
    ('360', 'Problemas y servicios sociales', 'division', '300'),
    ('370', 'Educación', 'division', '300'),
    ('380', 'Comercio, comunicaciones y transporte', 'division', '300'),
    ('390', 'Costumbres, etiqueta y folclore', 'division', '300'),
    ('410', 'Lingüística', 'division', '400'),
    ('420', 'Inglés e inglés antiguo', 'division', '400'),
    ('430', 'Lenguas germánicas, alemán', 'division', '400'),
    ('440', 'Lenguas romances, francés', 'division', '400'),
    ('450', 'Italiano, rumano y retorrománico', 'division', '400'),
    ('460', 'Español y portugués', 'division', '400'),
    ('470', 'Lenguas itálicas, latín', 'division', '400'),
    ('480', 'Lenguas helénicas, griego clásico', 'division', '400'),
    ('490', 'Otras lenguas', 'division', '400'),
    ('510', 'Matemáticas', 'division', '500'),
    ('520', 'Astronomía y ciencias afines', 'division', '500'),
    ('530', 'Física', 'division', '500'),
    ('540', 'Química y ciencias afines', 'division', '500'),
    ('550', 'Ciencias de la Tierra', 'division', '500'),
    ('560', 'Paleontología y paleozoología', 'division', '500'),
    ('570', 'Ciencias de la vida, biología', 'division', '500'),
    ('580', 'Plantas (botánica)', 'division', '500'),
    ('590', 'Animales (zoología)', 'division', '500'),
    ('610', 'Medicina y salud', 'division', '600'),
    ('620', 'Ingeniería y operaciones afines', 'division', '600'),
    ('630', 'Agricultura y tecnologías afines', 'division', '600'),
    ('640', 'Economía doméstica y vida familiar', 'division', '600'),
    ('650', 'Gestión y servicios auxiliares', 'division', '600'),
    ('660', 'Ingeniería química', 'division', '600'),
    ('670', 'Manufactura', 'division', '600'),
    ('680', 'Manufactura para usos específicos', 'division', '600'),
    ('690', 'Construcción de edificios', 'division', '600'),
    ('710', 'Urbanismo y arquitectura del paisaje', 'division', '700'),
    ('720', 'Arquitectura', 'division', '700'),
    ('730', 'Artes plásticas y escultura', 'division', '700'),
    ('740', 'Dibujo y artes decorativas', 'division', '700'),
    ('750', 'Pintura', 'division', '700'),
    ('760', 'Artes gráficas y grabado', 'division', '700'),
    ('770', 'Fotografía', 'division', '700'),
    ('780', 'Música', 'division', '700'),
    ('790', 'Artes recreativas y escénicas', 'division', '700'),
    ('810', 'Literatura estadounidense en inglés', 'division', '800'),
    ('820', 'Literatura inglesa e inglesa antigua', 'division', '800'),
    ('830', 'Literaturas germánicas, literatura alemana', 'division', '800'),
    ('840', 'Literaturas romances, literatura francesa', 'division', '800'),
    ('850', 'Literaturas italiana, rumana y retorrománica', 'division', '800'),
    ('860', 'Literaturas española y portuguesa', 'division', '800'),
    ('870', 'Literaturas itálicas, literatura latina', 'division', '800'),
    ('880', 'Literaturas helénicas, literatura griega clásica', 'division', '800'),
    ('890', 'Literaturas de otras lenguas', 'division', '800'),
    ('910', 'Geografía y viajes', 'division', '900'),
    ('920', 'Biografía y genealogía', 'division', '900'),
    ('930', 'Historia del mundo antiguo (hasta ca. 499)', 'division', '900'),
    ('940', 'Historia general de Europa', 'division', '900'),
    ('950', 'Historia general de Asia', 'division', '900'),
    ('960', 'Historia general de África', 'division', '900'),
    ('970', 'Historia general de América del Norte', 'division', '900'),
    ('980', 'Historia general de América del Sur', 'division', '900'),
    ('990', 'Historia general de otras áreas', 'division', '900');
